name: Publish
on:
  release:
    types: [publish]
  workflow_dispatch:
concurrency:
  group: publish
  cancel-in-progress: true
permissions: write-all
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  publish-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Andrew-Chen-Wang/github-wiki-action@v4
  publish-docs:
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
      - run: npm ci
      - uses: actions/configure-pages@v3
      - run: npm run build-docs
      - uses: actions/upload-pages-artifact@v1
        path: docs/dist
      - uses: actions/deploy-pages@v2
        id: deploy-pages
